-- 게이트웨이 배치 플래너 (function_gateway_planner.html Phase 1)
CREATE TABLE gateway_plan_jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(300) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  original_key TEXT NOT NULL,
  original_name VARCHAR(300) NOT NULL,
  page_index INTEGER NOT NULL DEFAULT 0,
  page_count INTEGER,
  image_key TEXT,
  vision_key TEXT,
  image_width INTEGER,
  image_height INTEGER,
  vision_width INTEGER,
  vision_height INTEGER,
  scale_m_per_px DOUBLE PRECISION,
  scale_source VARCHAR(20),
  scale_meta JSONB,
  analysis JSONB,
  placements JSONB,
  gateway_count INTEGER,
  rules_snapshot JSONB,
  pptx_key TEXT,
  error_message TEXT,
  token_usage JSONB,
  created_by TEXT NOT NULL REFERENCES users(id),
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX gateway_plan_jobs_created_by_created_at_idx ON gateway_plan_jobs (created_by, created_at DESC);
CREATE INDEX gateway_plan_jobs_created_at_idx ON gateway_plan_jobs (created_at DESC);

-- 메인 네비 + 설정 하위 메뉴 (접근 ADMIN 이상)
INSERT INTO nav_menu_items (menu_key, label, href, icon_key, parent_key, allowed_roles, allowed_org_codes, is_active, sort_order, group_label, updated_at)
VALUES
 ('gateway-planner', 'GW 배치 플래너', '/gateway-planner', 'wifi', NULL, '{SUPER_ADMIN,ADMIN}', '{}', true, 62, NULL, CURRENT_TIMESTAMP),
 ('settings/gateway-planner', 'GW 배치 규칙', '/settings/gateway-planner', NULL, 'settings', '{SUPER_ADMIN,ADMIN}', '{}', true, 110, '도구', CURRENT_TIMESTAMP)
ON CONFLICT (menu_key) DO NOTHING;
